port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info

proxies:
  - name: "VMESS-东京"
    type: vmess
    server: hy2cn.duckdns.org
    port: 8443
    uuid: "27484d4f-9352-40b0-954a-6798f1114741"
    tls: true
    servername: hy2cn.duckdns.org
    alterId: 0
    cipher: auto
    udp: true
    skip-cert-verify: true
    network: tcp

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "VMESS-东京"
      - "DIRECT"

rules:
  - IP-CIDR,193.108.118.153/32,VMESS-东京,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - MATCH,Proxy
